dataset_name: trl-internal-testing/tldr-preference-sft-trl-style
model_name_or_path: meta-llama/Llama-3.2-3B
dataset_test_split: validation
per_device_train_batch_size: 1
per_device_eval_batch_size: 2
learning_rate: 1.41e-5
gradient_accumulation_steps: 8
num_train_epochs: 1
logging_steps: 10
eval_strategy: steps
eval_steps: 400
save_strategy: steps
save_steps: 800
run_name: l32-3b-tldr-sft
output_dir: outputs/l32-3b-tldr-sft
warmup_ratio: 0.1
remove_unused_columns: False
report_to: wandb
dataset_num_proc: 32
packing: True
dataset_text_field: text
bf16: True

use_peft: False
lora_r: 64
lora_alpha: 128
lora_dropout: 0.05
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj